# Generated by Django 5.1.3 on 2024-11-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bots",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("events", models.JSONField()),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=15)),
                ("website", models.URLField(blank=True, null=True)),
                ("message", models.TextField()),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="Información del navegador y dispositivo del usuario",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "referrer",
                    models.URLField(
                        blank=True, help_text="URL de referencia", null=True
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Dirección IP del usuario", null=True
                    ),
                ),
                (
                    "session_duration",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duración de la sesión en segundos",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha y hora de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Fecha y hora de última actualización"
                    ),
                ),
            ],
        ),
    ]
